### ISSUE TITLE
SortedSet extracted from set add sorted_set gem to runtime dependencies

### ISSUE THREAD

**Issue by briancolfer-upstart** [commander-rb/commander#98]

**Comment by ggilder** [comment]
I don't understand this issue, please provide some context on what problem you're seeing.

**Comment by briancolfer-upstart** [comment]
When I run the rspec tests I get:

**Comment by ggilder** [comment]
Thank you, that helps. I don't think requiring the `sorted_set` gem is the ideal solution though — this `AskForClass` code has been problematic with a number of these constants that get deprecated over time, and it would be great to have a more permanent solution. Feel free to put together a PR if that makes sense, otherwise I will try to revise the logic.

**Comment by ggilder** [comment]
It looks like this issue only occurs on Ruby 3, per https://dev.to/aaronc81/removing-functionality-the-ruby-way-a-look-into-sortedset-on-ruby-3-clf

**Comment by ggilder** [comment]
Fixed in version 4.6.0 (just released). Thanks for flagging this!
